# Generated by Django 4.1.6 on 2023-03-31 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part_ad', '0002_alter_carpart_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='part_ad.user'),
        ),
    ]
