name: ESLint
on:
  push:
    branches:
      - main
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install --prefix frontend
      - name: Install ESLint Vue plugin
        run: npm install --prefix frontend eslint-plugin-vue
      - name: Run ESLint
        run: npx eslint --config frontend/.eslintrc.yml --ext .js,.vue src
