name: Run Pylint
on:
  push:
    branches:
      - main
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Change working directory to backend
        run: cd backend
      - name: Print working directory
        run: pwd
      - name: Add user permissions
        run: chmod +r requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Pylint on car_part_finder_pro app
        run: pylint car_part_finder_pro
      - name: Run Pylint on part_ad app
        run: pylint part_ad
